const QUESTIONS = [
	{ prompt: "Em qual etapa ocorre o crossing-over na meiose?", answer: "profase i", type: "media" },
	{ prompt: "Qual processo gera duas celulas-filhas geneticamente identicas?", answer: "mitose", type: "facil" },
	{ prompt: "A meiose reduz o numero de cromossomos pela metade. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "A meiose possui quantas divisoes celulares principais?", answer: "2", type: "facil" },
	{ prompt: "Na meiose I, o que se separa primeiro: cromossomos homologos ou cromatides irmas?", answer: "cromossomos homologos", type: "media" },
	{ prompt: "Na mitose, em que fase os cromossomos se alinham no plano equatorial?", answer: "metafase", type: "facil" },
	{ prompt: "Qual fase da meiose separa cromatides irmas?", answer: "anafase ii", type: "media" },
	{ prompt: "Celulas somaticas se dividem principalmente por mitose ou meiose?", answer: "mitose", type: "facil" },
	{ prompt: "Gametas sao produzidos por mitose ou meiose?", answer: "meiose", type: "facil" },
	{ prompt: "Qual estrutura une as cromatides irmas?", answer: "centromero", type: "facil" },
	{ prompt: "A variabilidade genetica aumenta com crossing-over. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Na meiose II, o numero de cromossomos e reduzido novamente? (sim/nao)", answer: "nao", type: "media" },
	{ prompt: "Qual divisao celular forma quatro celulas-filhas ao final?", answer: "meiose", type: "facil" },
	{ prompt: "Mitose ocorre em celulas germinativas para formar gametas. Verdadeiro ou falso?", answer: "falso", type: "verdadeiro_falso" },
	{ prompt: "Nome da fase em que a carioteca se desorganiza:", answer: "profase", type: "facil" },
	{ prompt: "Cromossomos homologos possuem genes para as mesmas caracteristicas. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Em qual fase da mitose as cromatides irmas se separam?", answer: "anafase", type: "facil" },
	{ prompt: "O que e um gameta?", answer: "celula sexual", type: "facil" },
	{ prompt: "Quantos cromossomos ha em um gameta humano?", answer: "23", type: "media" },
	{ prompt: "Quantos cromossomos ha em uma celula somatica humana?", answer: "46", type: "media" },
	{ prompt: "Em qual fase ocorre o pareamento dos cromossomos homologos?", answer: "profase i", type: "media" },
	{ prompt: "Qual nome do processo que gera variabilidade genetica pela troca de segmentos?", answer: "crossing over", type: "media" },
	{ prompt: "O que e diploide?", answer: "2n", type: "facil" },
	{ prompt: "O que e haploide?", answer: "n", type: "facil" },
	{ prompt: "Qual fase finaliza a meiose I?", answer: "telofase i", type: "media" },
	{ prompt: "Qual fase finaliza a meiose II?", answer: "telofase ii", type: "media" },
	{ prompt: "A meiose produz quantas celulas-filhas?", answer: "4", type: "facil" },
	{ prompt: "A mitose produz quantas celulas-filhas?", answer: "2", type: "facil" },
	{ prompt: "Os cromossomos homologos se separam em qual fase?", answer: "anafase i", type: "media" },
	{ prompt: "Os cromossomos se alinham em pares em qual fase da meiose I?", answer: "metafase i", type: "media" },
	{ prompt: "A meiose ocorre em qual tipo de celula para formar gametas?", answer: "celula germinativa", type: "media" },
	{ prompt: "A mitose e responsavel por crescimento e reparo. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Qual e o nome do conjunto completo de cromossomos de uma especie?", answer: "cariotipo", type: "media" },
	{ prompt: "Qual e a funcao do fuso mitotico?", answer: "separar cromossomos", type: "media" },
	{ prompt: "Em que fase a membrana nuclear reaparece?", answer: "telofase", type: "facil" },
	{ prompt: "A duplicacao do DNA ocorre em qual fase do ciclo celular?", answer: "fase s", type: "media" },
	{ prompt: "A meiose I e chamada de divisao reducional. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "A meiose II e chamada de divisao equacional. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Quando ocorre a citocinese?", answer: "no final da divisao", type: "media" },
	{ prompt: "Qual estrutura organiza o fuso e ancora microtubulos?", answer: "centriolo", type: "media" },
	{ prompt: "A variabilidade genetica vem de crossing-over e qual outro processo?", answer: "segregacao independente", type: "dificil" },
	{ prompt: "Qual fase antecede a profase?", answer: "interfase", type: "facil" },
	{ prompt: "Os cromossomos duplicados sao formados por duas cromatides irmas. Verdadeiro ou falso?", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Qual e a funcao da meiose?", answer: "formar gametas", type: "facil" },
	{ prompt: "A meiose ocorre em celulas somaticas. Verdadeiro ou falso?", answer: "falso", type: "verdadeiro_falso" },
	{ prompt: "Em qual fase os cromossomos se condensam?", answer: "profase", type: "facil" },
	{ prompt: "Em qual fase as cromatides irmas se separam na mitose?", answer: "anafase", type: "facil" },
	{ prompt: "Qual fase antecede a metafase?", answer: "profase", type: "facil" },
	{ prompt: "Qual fase sucede a anafase?", answer: "telofase", type: "facil" },
	{ prompt: "Qual e o nome da primeira divisao da meiose?", answer: "meiose i", type: "facil" },
	{ prompt: "Qual e o nome da segunda divisao da meiose?", answer: "meiose ii", type: "facil" },
	{ prompt: "A uniao de dois gametas forma o que?", answer: "zigoto", type: "facil" },
	{ prompt: "Qual e o nome da celula formada apos a fecundacao?", answer: "zigoto", type: "facil" },
	{ prompt: "Qual organela forma o fuso em celulas animais?", answer: "centriolo", type: "media" },
	{ prompt: "Quantas cromatides tem um cromossomo duplicado?", answer: "2", type: "facil" },
	{ prompt: "Cromossomos homologos sao identicos? (sim/nao)", answer: "nao", type: "media" },
	{ prompt: "A sinapse dos homologos ocorre em que fase?", answer: "profase i", type: "dificil" },
	{ prompt: "O quiasma e observado em qual fase?", answer: "profase i", type: "dificil" },
	{ prompt: "Pergunta especial: o que ganha pontos extras de todos os adversarios?", answer: "pergunta especial", type: "especial" },
	{ prompt: "Pergunta especial: o nome do processo de troca de segmentos?", answer: "crossing over", type: "especial" },
	{ prompt: "Pergunta especial: qual divisao reduz o numero de cromossomos?", answer: "meiose i", type: "especial" },
	{ prompt: "Pergunta especial: qual divisao separa cromatides irmas?", answer: "meiose ii", type: "especial" },
	{ prompt: "Multipla escolha: qual fase separa cromossomos homologos? a) profase i b) anafase i c) metafase ii", answer: "b", type: "multipla_escolha" },
	{ prompt: "Multipla escolha: qual e a funcao da mitose? a) formar gametas b) crescimento c) reduzir cromossomos", answer: "b", type: "multipla_escolha" },
	{ prompt: "Multipla escolha: em que fase ocorre o crossing-over? a) profase i b) telofase i c) anafase ii", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha: quantas celulas a meiose produz? a) 2 b) 3 c) 4", answer: "c", type: "multipla_escolha" },
	{ prompt: "Verdadeiro ou falso: a mitose reduz o numero de cromossomos pela metade.", answer: "falso", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: a meiose gera variabilidade genetica.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: a meiose ocorre em duas divisoes celulares.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: cromatides irmas se separam na meiose I.", answer: "falso", type: "verdadeiro_falso" },
	{ prompt: "Multipla escolha (2 alternativas): a meiose reduz o numero de cromossomos? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): a mitose gera duas celulas-filhas identicas? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): gametas sao formados por meiose? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): a fase em que cromossomos se alinham e a metafase? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): crossing-over ocorre na profase I? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): a meiose II separa cromossomos homologos? a) sim b) nao", answer: "b", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): a mitose reduz cromossomos pela metade? a) sim b) nao", answer: "b", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): cromossomos homologos se separam na anafase I? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): telofase marca o fim da divisao? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Multipla escolha (2 alternativas): a meiose gera 4 celulas-filhas? a) sim b) nao", answer: "a", type: "multipla_escolha" },
	{ prompt: "Verdadeiro ou falso: a meiose forma quatro celulas-filhas haploides.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: cromossomos homologos se pareiam na profase I.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: a meiose ocorre em celulas somaticas.", answer: "falso", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: a mitose gera variabilidade genetica.", answer: "falso", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: a separacao de cromatides irmas na meiose ocorre na anafase II.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: o DNA se duplica na interfase.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: o zigoto e formado pela uniao de dois gametas.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: a citocinese separa o citoplasma ao final da divisao.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: o fuso mitotico ajuda a separar cromossomos.", answer: "verdadeiro", type: "verdadeiro_falso" },
	{ prompt: "Verdadeiro ou falso: cromossomos homologos sao iguais em tudo, sem variacoes.", answer: "falso", type: "verdadeiro_falso" }
];
